### ISSUE TITLE
Runtime Exception w/ Java 8 Lambas in Android

### ISSUE THREAD

**Issue by kylemallory** [zeromq/jeromq#627]
I did a build from the latest master snapshot on Github, and ran into this error when receiving data on the REP socket.
```
I/art: Rejecting re-init on previously-failed class java.lang.Class<zmq.io.StreamEngine$ProducePongMessage>
    Rejecting re-init on previously-failed class java.lang.Class<zmq.io.StreamEngine$ProducePongMessage>
I/art: Rejecting re-init on previously-failed class java.lang.Class<zmq.io.-$$Lambda$StreamEngine$W0Gv5o5INYywwEmQ5W1uv6x5Tgw>
E/AndroidRuntime: FATAL EXCEPTION: iothread-2
    Process: com.ravn.havoc, PID: 21413
    java.lang.NoClassDefFoundError: zmq.io.-$$Lambda$StreamEngine$W0Gv5o5INYywwEmQ5W1uv6x5Tgw
        at zmq.io.StreamEngine.<init>(StreamEngine.java:865)
        at zmq.io.net.tcp.TcpConnecter.connectEvent(TcpConnecter.java:149)
        at zmq.io.IOObject.connectEvent(IOObject.java:99)
        at zmq.poll.Poller.run(Poller.java:267)
        at java.lang.Thread.run(Thread.java:818)
```
The stack references these lines in StreamEngine.java:
```
    private final Function<Msg, Boolean> processIdentity = this::processIdentityMsg;
    private final Supplier<Msg>          nextIdentity    = this::identityMsg;
```

Its not clear to me why this is throwing the error...

**Comment by kylemallory** [comment]
That's exactly the problem.  Android doesn't fully support Java 8. Hence, its not something I can fix by upgrading to Java 8.  Rather, by switching to Java 8 (or at least taking advantage of Java 8 syntactic sugar), its now broken for *all* Android development.  With Java 7's EOL we can hope hope for a quick resolution from Google/Android, but it may mean JeroMQ loses a number of users.  I really enjoy working with ZMQ, but it *has* to work with my platform.

**Comment by fredoboulo** [comment]
Did you try: https://developer.android.com/studio/write/java8-support ?

I remember the Android topic was raised when decision was made to go to java 8. Feedback was that it was possible for Android users to make the move.

**Comment by kylemallory** [comment]
Thanks, I'm familiar with this, but I'll go through it again, and make sure I didn't miss anything.

**Comment by fredoboulo** [comment]
Did you make any progress on this? I'm not very enthusiastic at the idea to revert back to Java 7, but if it's for the good of the users...

**Comment by dasgarner** [comment]
I've also encountered this issue - but I get some different results depending on the device that I install on. Android project updated with Java8 support as per the android developer guide.

With a device running Android 7, no problems

With a device running Android 6.0.1, I get:

```
java.lang.NoClassDefFoundError: zmq.io.-$$Lambda$StreamEngine$W0Gv5o5INYywwEmQ5W1uv6x5Tgw
        at zmq.io.StreamEngine.<init>(StreamEngine.java:876)
        at zmq.io.net.tcp.TcpConnecter.connectEvent(TcpConnecter.java:145)
        at zmq.io.IOObject.connectEvent(IOObject.java:99)
        at zmq.poll.Poller.run(Poller.java:267)
        at java.lang.Thread.run(Thread.java:818)
```

And with a device running 4.4.4 I get:

```
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.newKeySet
        at org.zeromq.ZContext.<init>(ZContext.java:88)
        at org.zeromq.ZContext.<init>(ZContext.java:83)
        at org.zeromq.ZContext.<init>(ZContext.java:78)
```

All 3 of these run the prior version 0.4.3 - i'm updating to 0.5 to solve a problem I get with sockets not reconnecting after a long period of network inactivity.

Happy to do anything needed to debug further.

**Comment by fredoboulo** [comment]
I think I understand now, it's not about the syntaxic sugar, but the fact that not every classes or packages are included in every flavour of Android.

I listed so far:

- added in API level 24
java.util.function classes
java.util.stream classes
java.util.Optional
java.lang.FunctionalInterface

- added in API level 19
java.util.Objects

I was about to create a PR, I'm introducing removals of these usages.
I just have a doubt about the 2 draft APIs, ZMQ.recvStream. @esahekmat you introduced them, would you mind if I remove them for the time being? Unless someone gets a better idea...

If someone can propose a more exhaustive list, that wuld be helpful, as well as a way to build the library with a given version of Android on Travis

**Comment by esahekmat** [comment]
Of course, they are draft version and I think support Android users is more important than two draft API.

**Comment by dasgarner** [comment]
Hi! I saw there was a 0.5.1 release which contained the above commits (thanks), however on testing I still see issues:

On Android 6.0.1:
```
java.lang.NoSuchMethodError: No static method stream([Ljava\/lang\/Object;)Ljava\/util\/stream\/Stream; in class Ljava\/util\/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in \/system\/framework\/core-libart.jar)
	at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:139)
	at zmq.io.net.tcp.TcpAddress.<init>(TcpAddress.java:40)
	at zmq.io.net.Address.resolve(Address.java:93)
	at zmq.SocketBase.connect(SocketBase.java:549)
	at org.zeromq.ZMQ$Socket.connect(ZMQ.java:3069)
```

On Android 4.4.4:
```
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.newKeySet
    at org.zeromq.ZContext.<init>(ZContext.java:88)
    at org.zeromq.ZContext.<init>(ZContext.java:83)
    at org.zeromq.ZContext.<init>(ZContext.java:78)
```

Once again Android 7+ has no such issues.

**Comment by lgawin** [comment]
@dasgarner fix for this issue is already merged: https://github.com/zeromq/jeromq/pull/710 and  `0.5.2-SNAPSHOT` works well.

So we just need new release. Are there any plans for `0.5.2` version?

**Comment by dasgarner** [comment]
Thanks for letting me know - i'm keen to try out 0.5.2 as well (and perhaps this issue can get closed out as a result).

**Comment by trevorbernard** [comment]
Sounds like a good time to cut a new release. Once the Changelog is updated then we'll release a new version

**Comment by esahekmat** [comment]
Isn't it better to fix #729 before release, I think that is a serious bug

**Comment by fredoboulo** [comment]
`ConcurrentHashMap.newKeySet` is still called in ZContext, so next 0.5.2 as it is will most probably not work on Android 4.4.4

**Comment by esahekmat** [comment]
Is there any issue related to this `ConcurrentHashMap.newKeySet`?
does replace them with `Collections.newSetFromMap(new ConcurrentHashMap<>())` solve the problem?

**Comment by MatFl** [comment]
Any news on the 0.5.2 release?

**Comment by daveyarwood** [comment]
A new release is certainly overdue! The last release, 0.5.1, was in April 2019.

I'll get the ball rolling on the next release.

**Comment by daveyarwood** [comment]
[0.5.2](https://mvnrepository.com/artifact/org.zeromq/jeromq/0.5.2) is available now.

@trevorbernard Can you update the mailing list?

**Comment by daveyarwood** [comment]
Based on the conversation above, it sounds like the issue was probably fixed in 0.5.2, so I'm going to close this. Feel free to reopen if the issue persists in the latest release.
